### ISSUE TITLE
Alert users of yf limits

### ISSUE THREAD

**Issue by msperlin** [msperlin/yfR#9]
- make sure users know that their download failed due to yf limits..

**Comment by tplaiho777** [comment]
Hi,

Thank you for your efforts to give us free financial data to r. 

It is very valuable work and I highly respect it.  It has helped me to do my master's thesis at uwasa. 

However, I have had a few problems: 

1. If I try to download all stock price info from the SP500 package I can't get them all, only 351 or something like that. 
2. If I try to get FTSE or BIOV I can't get them. 

I downloaded the latest yfR package from your site a moment ago. 

Thank you very much if you can help me. 



I am using the following script: 

##########LYHYTVERSIO MONTHLY###########################

library(utils)
library(yfR)
library(ggplot2)
library(dplyr)
library(zoo)
library(xts)
library(remotes)
library(openssl)
library(globals)
library(future)
library(humanize

my_ticker <- 'SP 500'
first_date <- '2000-01-01'
last_date <-  '2022-05-31'

df_daily <- yf_get(tickers = my_ticker, 
                     first_date, last_date, 
                     freq_data = 'daily')  %>%
  mutate(freq = 'daily')

df_allfreq <- bind_rows(
  list(df_daily)
) %>%
  mutate(freq = factor(freq, 
                       levels = c('df_daily'))) # make sure the order in plot is right

p <- ggplot(df_allfreq, aes(x=ref_date, y = price_close)) + 
  geom_point() + geom_line() + facet_grid(freq ~ ticker) + 
  theme_minimal() + 
  labs(x = '', y = 'Close Prices')

View(p)


The problem is here: 


![Screenshot 2022-06-03 221630](https://user-images.githubusercontent.com/81896612/171933831-f5fe7f84-2d54-4a99-b6ec-515338dc4bcb.jpg)

Any hope with Yahoo to solve this?

**Comment by msperlin** [comment]
Hi @tplaiho777

It seems you missed the SP500 ticker. It is ^GSPC (and not SP500).

**Comment by msperlin** [comment]
if you want the whole sp500 components, use yf_collection_get(). 

See vignette here: https://msperlin.github.io/yfR/articles/using-collections.html

**Comment by msperlin** [comment]
This is fixed now. Whenever the returned tickers are less than 50% of requested tickers, the function will throw a cli danger message. 

584c21959369064ad6fffe23a1444392e3c6cfc9

**Comment by tplaiho777** [comment]
Hi,

Many thanks for your efforts. Perhaps due to some other error, I do not get all the files from SP500. 

1. If I use ticker ^GSPC, it will not work at all.
2. If I use ticker SP500 it works but when I have downloaded 354 tickers the cache may be filled and It will not download those anymore. I would like to have all 500.  

How do I enlarge my cache, if that is the reason? Please let me know why I do not get FTSE at all, and the third files from brazil are impossible to download also. 

Here is some visual info: 

![Screenshot 2022-06-03 221630](https://user-images.githubusercontent.com/81896612/172440810-8a76999b-4040-43da-ab1b-72e439e968eb.jpg)

![Uploading Screenshot 2022-06-07 195802.jpg…]()

Please help if you have time for me. 

I also do not get yahoo files to Finland in any other way but by using r -software. It is some regional reason which makes my options limited. I do not know if that has something to do with this R also.

**Comment by msperlin** [comment]
@tplaiho777 can you please post code (and not figures). Otherwise I cant replicate what youre doing..

**Comment by tplaiho777** [comment]
I just updated an hour ago

**Comment by tplaiho777** [comment]
devtools::install_github('msperlin/yfR') I used this to update...

**Comment by msperlin** [comment]
did you upgrade quantmod?

**Comment by tplaiho777** [comment]
No, But I will do it for next....

**Comment by tplaiho777** [comment]
...and FTSE does not download at all.

**Comment by msperlin** [comment]
It worked fine here:

`library(yfR)

df_yf <- yf_collection_get("SP500")

head(df_yf)`
 

![image](https://user-images.githubusercontent.com/10583352/172445794-fc56f718-feff-438d-a46b-aa19841a886c.png)

**Comment by msperlin** [comment]
did you restart your R session?

**Comment by msperlin** [comment]
likelly you reached YF limits.. update all your packages,  close RStudio and try again in 15 minutes.. 

Let me know how it goes..

**Comment by tplaiho777** [comment]
Ok, I will do it. Thanks!

**Comment by tplaiho777** [comment]
15 minutes break did not help....sigh. I wonder what causes this.....?

**Comment by msperlin** [comment]
are you in a restricted network (e.g. universities)?

**Comment by tplaiho777** [comment]
No, normal system, I would say.

**Comment by msperlin** [comment]
copy and paste the result of `sessionInfo()`. Lets see whats the issue..
